# Alpine is used instead of a scratch image in order to bring in SSL support and CAs.
FROM alpine:3.4

RUN apk --update add go ca-certificates

COPY . /go/src/github.com/cloudflare/complainer

RUN export GOPATH=/go GO15VENDOREXPERIMENT=1 && \
    go get github.com/cloudflare/complainer/...

RUN mkdir /var/log/mesos-complainer
RUN chown nobody:nobody /var/log/mesos-complainer

USER nobody

ENTRYPOINT ["/go/bin/complainer"]
